---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-private-key
        exclude: ^environments/1\.local/
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["--severity=error"]
        exclude: "^.git"
        files: "\\.sh$"

  - repo: https://github.com/ansible/ansible-lint
    rev: v6.22.2
    hooks:
      - id: ansible-lint
        additional_dependencies:
          - ansible-core>=2.12,<2.16
          - jmespath==1.0.1
          - netaddr==1.3.0
          - distlib
        args: [--config-file=.ansible-lint.yml]

  - repo: https://github.com/golangci/misspell
    rev: v0.6.0
    hooks:
      - id: misspell

  - repo: https://github.com/ansible/ansible-lint
    rev: v6.22.2
    hooks:
      - id: ansible-lint
        additional_dependencies:
          - ansible-core>=2.12,<2.16
          - jmespath==1.0.1
          - netaddr==1.3.0
          - distlib
        args:
          - -x
          - var-naming[no-jinja]
