---
# handlers file for ansible-role-pgbouncer
- name: PgBouncer - Restart container
  community.docker.docker_container:
    name: "{{ pgbouncer_container_name }}"
    state: started
    restart: true
  when: pgbouncer_container_info.container.State.Running | default(false)
  tags: pgbouncer
